this.tokens = {
    API_KEY : 'YOUR_API_KEY_HERE'
  , CONSUMER_KEY : 'YOUR_CONSUMER_KEY_HERE'
  , CONSUMER_SECRET : 'YOUR_CONSUMER_SECRET_HERE'
  , OAUTH_TOKEN : 'YOUR_ACCESS_TOKEN_HERE'
  , OAUTH_TOKEN_SECRET : 'YOUR_ACCESS_TOKEN_SECRET_HERE'
};